### ISSUE TITLE
Updating team page

### ISSUE THREAD

**Issue by trouille** [zooniverse/wisconsin-wildlife-watch-team#1]
@mcbouslog With the switch to the Snapshot WI branding of the WI Wildlife Watch site (i.e., https://www.zooniverse.org/lab/2439 and snapshotwisconsin.org instead of wisconsinwildlifewatch.org), the research team has requested a few updates to the team page. 

(Eventually the research team will be able to make updates themselves to the team page via the new 'About' setup that you and Will are working on. But because they're doing a demo on Wednesday to their funding agency for this project, we need to implement these changes now for them in the existing external team site. Also, since their current 'team' page has separate tabs for organizations and credits, I'll need to figure out with them how they want to transfer the info to just the 'Team' section. Finally -- Even if the new Project Builder 'About' has a PR this week, we'll need to send a newsletter to research teams to let them know this change in the interface is about to happen -- I'll be working with Grant this week to put together that newsletter. We'd hold off on merging the PR until that newsletter has gone out).

I'd like if you could pause other work on Monday and prioritize getting this done first. My hope is you can have these changes in place and public by end of day Monday. 

**Updates needed:**
- Change URL from http://zooniverse.github.io/wisconsin-wildlife-watch-team/public/ to http://zooniverse.github.io/snapshot-wisconsin-team/public/
- Change all references in the text from Wisconsin Wildlife Watch to Snapshot Wisconsin

On Image Credits tab, delete:
- Both beaver images
- Muskrat image
- Male pheasant image (2nd image)
- Both whooping crane images
- Woodchuck image

Add the following to the People and Organizations tab: 
- Dr. Jennifer Stenglein is a quantitative wildlife research scientist with the Wisconsin Department of Natural Resources where she works on trail camera monitoring of Wisconsin’s wildlife.  She is interested in getting students and the public involved in wildlife monitoring and using those data to understand spatial patterns and temporal trends in wildlife populations.
- Christina Locke is a research scientist for the Wisconsin Department of Natural Resources. She enjoys working at the intersection of science, policy, and outreach, and has particular interests in citizen science and GIS. Christina received her Bachelor's degree in Biology from the University of Wisconsin-Eau Claire and her PhD in Land Use Policy from the University of Wisconsin-Madison.
- Susan Frett is a natural resources educator for the Wisconsin Department of Natural Resources, with primary responsibilities including outreach using social media, volunteer recruitment and training.  Her interest is in engaging citizens in nature and science based activities in order to help people develop a conservation ethic.  Susan received her Bachelor’s degree in Environmental Science from the University of Iowa and her Master’s degree in Environmental Conservation from the University of Wisconsin-Madison.
- Wisconsin Department of Natural Resources
  Members of the Snapshot Wisconsin team are scientists at the Wisconsin Department of Natural Resources (WDNR). The WDNR provided funding for the purchase of trail cameras and provides ongoing support for the project. The WDNR, in partnership with individuals and organizations, manages “fish, wildlife, forests, parks, air and water resources while promoting a healthy, sustainable environment and a full range of outdoor opportunities.”

(For WI Dep't of Natural Resources, use this image: http://www.northwoodsbass.com/wp-content/uploads/2015/09/DNRlogoprocess.png)

For the people, use the attached photos. 
![bio photo_sfv2](https://cloud.githubusercontent.com/assets/4975655/14942331/07b09e88-0f7f-11e6-90df-bcd498c13d54.jpg)
![locke](https://cloud.githubusercontent.com/assets/4975655/14942329/07afde76-0f7f-11e6-8bd1-46bb46093d0c.JPG)
![stenglein pic2](https://cloud.githubusercontent.com/assets/4975655/14942330/07aff3fc-0f7f-11e6-90df-a6470d4922b6.jpg)

**Comment by trouille** [comment]
![logo_semisimple](https://cloud.githubusercontent.com/assets/4975655/14959168/a2a1517e-1053-11e6-99fe-7e1ac633b911.jpg)

**Comment by mcbouslog** [comment]
Issue moved to [zooniverse/snapshot-wisconsin-team #1](https://github.com/zooniverse/snapshot-wisconsin-team/issues/1) via [**ZenHub.io**](https://www.zenhub.io/)
